from django.db import models

class Hospital(models.Model):
    hospital_name = models.CharField(max_length=60, unique=True)

    def __str__(self):
        return '{}'.format(self.hospital_name)

class Department(models.Model):
    department_name = models.CharField(max_length=60, unique=True)
    hospital_department = models.ForeignKey(Hospital, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.department_name)

class Doctor(models.Model):
    doctor_name = models.CharField(max_length=60, unique=True)
    hospital_doctor = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    department_doctor = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.doctor_name)

class Anketa(models.Model):
    personal_number = models.DecimalField(max_digits=30, unique=True, decimal_places=0)
    data_time = models.DateTimeField(auto_now_add=True, null=True)
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    age = models.DecimalField(max_digits=3, decimal_places=0)
    gender = models.CharField(max_length=30, verbose_name='Пол')
    q1 = models.DecimalField(max_digits=1, decimal_places=0)
    q2 = models.DecimalField(max_digits=1, decimal_places=0)
    q3 = models.DecimalField(max_digits=1, decimal_places=0)
    q4 = models.DecimalField(max_digits=1, decimal_places=0)
    q5 = models.DecimalField(max_digits=1, decimal_places=0)
    q6 = models.DecimalField(max_digits=1, decimal_places=0)
    q7 = models.DecimalField(max_digits=1, decimal_places=0)
    q8 = models.DecimalField(max_digits=1, decimal_places=0)
    q9 = models.DecimalField(max_digits=1, decimal_places=0)
    q10 = models.DecimalField(max_digits=1, decimal_places=0)
    q11 = models.DecimalField(max_digits=1, decimal_places=0)
    q12 = models.DecimalField(max_digits=1, decimal_places=0)
    q13 = models.DecimalField(max_digits=1, decimal_places=0)
    q14 = models.DecimalField(max_digits=1, decimal_places=0)
    q15 = models.DecimalField(max_digits=1, decimal_places=0)
    q16 = models.DecimalField(max_digits=1, decimal_places=0)
    q17 = models.DecimalField(max_digits=1, decimal_places=0)
    q18 = models.DecimalField(max_digits=1, decimal_places=0)
    q19 = models.DecimalField(max_digits=1, decimal_places=0)
    q20 = models.DecimalField(max_digits=1, decimal_places=0)
    q21 = models.DecimalField(max_digits=1, decimal_places=0)
    q22 = models.DecimalField(max_digits=1, decimal_places=0)
    q23 = models.DecimalField(max_digits=1, decimal_places=0)
    q24 = models.DecimalField(max_digits=1, decimal_places=0)
    q25 = models.DecimalField(max_digits=1, decimal_places=0)
    q26 = models.DecimalField(max_digits=1, decimal_places=0)
    q27 = models.DecimalField(max_digits=1, decimal_places=0)
    q28 = models.DecimalField(max_digits=1, decimal_places=0)
    q29 = models.DecimalField(max_digits=1, decimal_places=0)
    q30 = models.DecimalField(max_digits=1, decimal_places=0)
    q31 = models.DecimalField(max_digits=1, decimal_places=0)
    q32 = models.DecimalField(max_digits=1, decimal_places=0)
    q33 = models.DecimalField(max_digits=1, decimal_places=0)
    q34 = models.DecimalField(max_digits=1, decimal_places=0)
    q35 = models.DecimalField(max_digits=1, decimal_places=0)
    q36 = models.DecimalField(max_digits=1, decimal_places=0)
    q37 = models.DecimalField(max_digits=1, decimal_places=0)
    q38 = models.DecimalField(max_digits=1, decimal_places=0)
    q39 = models.DecimalField(max_digits=1, decimal_places=0)
    q40 = models.DecimalField(max_digits=1, decimal_places=0)
    result_treatment = models.DecimalField(max_digits=2, decimal_places=0, null=True)
    result_relationship = models.DecimalField(max_digits=2, decimal_places=0, null=True)
    result_stigma = models.DecimalField(max_digits=2, decimal_places=0, null=True)
    result_condition = models.DecimalField(max_digits=2, decimal_places=0, null=True)
    result_total = models.DecimalField(max_digits=2, decimal_places=0, null=True)

    def __str__(self):
        return '{}'.format(self.personal_number)

class FakeAnketa(models.Model):
    personal_number = models.DecimalField(max_digits=30, unique=True, decimal_places=0)
    data_time = models.DateTimeField(auto_now_add=True, null=True)
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    age = models.DecimalField(max_digits=3, decimal_places=0)
    gender = models.CharField(max_length=30, verbose_name='Пол')
    q1 = models.DecimalField(max_digits=1, decimal_places=0)
    q2 = models.DecimalField(max_digits=1, decimal_places=0)
    q3 = models.DecimalField(max_digits=1, decimal_places=0)
    q4 = models.DecimalField(max_digits=1, decimal_places=0)
    q5 = models.DecimalField(max_digits=1, decimal_places=0)
    q6 = models.DecimalField(max_digits=1, decimal_places=0)
    q7 = models.DecimalField(max_digits=1, decimal_places=0)
    q8 = models.DecimalField(max_digits=1, decimal_places=0)
    q9 = models.DecimalField(max_digits=1, decimal_places=0)
    q10 = models.DecimalField(max_digits=1, decimal_places=0)
    q11 = models.DecimalField(max_digits=1, decimal_places=0)
    q12 = models.DecimalField(max_digits=1, decimal_places=0)
    q13 = models.DecimalField(max_digits=1, decimal_places=0)
    q14 = models.DecimalField(max_digits=1, decimal_places=0)
    q15 = models.DecimalField(max_digits=1, decimal_places=0)
    q16 = models.DecimalField(max_digits=1, decimal_places=0)
    q17 = models.DecimalField(max_digits=1, decimal_places=0)
    q18 = models.DecimalField(max_digits=1, decimal_places=0)
    q19 = models.DecimalField(max_digits=1, decimal_places=0)
    q20 = models.DecimalField(max_digits=1, decimal_places=0)
    q21 = models.DecimalField(max_digits=1, decimal_places=0)
    q22 = models.DecimalField(max_digits=1, decimal_places=0)
    q23 = models.DecimalField(max_digits=1, decimal_places=0)
    q24 = models.DecimalField(max_digits=1, decimal_places=0)
    q25 = models.DecimalField(max_digits=1, decimal_places=0)
    q26 = models.DecimalField(max_digits=1, decimal_places=0)
    q27 = models.DecimalField(max_digits=1, decimal_places=0)
    q28 = models.DecimalField(max_digits=1, decimal_places=0)
    q29 = models.DecimalField(max_digits=1, decimal_places=0)
    q30 = models.DecimalField(max_digits=1, decimal_places=0)
    q31 = models.DecimalField(max_digits=1, decimal_places=0)
    q32 = models.DecimalField(max_digits=1, decimal_places=0)
    q33 = models.DecimalField(max_digits=1, decimal_places=0)
    q34 = models.DecimalField(max_digits=1, decimal_places=0)
    q35 = models.DecimalField(max_digits=1, decimal_places=0)
    q36 = models.DecimalField(max_digits=1, decimal_places=0)
    q37 = models.DecimalField(max_digits=1, decimal_places=0)
    q38 = models.DecimalField(max_digits=1, decimal_places=0)
    q39 = models.DecimalField(max_digits=1, decimal_places=0)
    q40 = models.DecimalField(max_digits=1, decimal_places=0)
    result_treatment = models.DecimalField(max_digits=2, decimal_places=0, null=True)
    result_relationship = models.DecimalField(max_digits=2, decimal_places=0, null=True)
    result_stigma = models.DecimalField(max_digits=2, decimal_places=0, null=True)
    result_condition = models.DecimalField(max_digits=2, decimal_places=0, null=True)
    result_total = models.DecimalField(max_digits=2, decimal_places=0, null=True)

    def __str__(self):
        return '{}'.format(self.personal_number)
