# Generated by Django 3.2.9 on 2023-03-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=40, unique=True)),
                ('department_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketa_app.department')),
                ('hospital_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketa_app.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='hospital_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketa_app.hospital'),
        ),
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_number', models.DecimalField(decimal_places=0, max_digits=30, unique=True)),
                ('data_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('gender', models.CharField(max_length=30, verbose_name='Пол')),
                ('q1', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q2', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q3', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q4', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q5', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q6', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q7', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q8', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q9', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q10', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q11', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q12', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q13', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q14', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q15', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q16', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q17', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q18', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q19', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q20', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q21', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q22', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q23', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q24', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q25', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q26', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q27', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q28', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q29', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q30', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q31', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q32', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q33', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q34', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q35', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q36', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q37', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q38', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q39', models.DecimalField(decimal_places=0, max_digits=1)),
                ('q40', models.DecimalField(decimal_places=0, max_digits=1)),
                ('result_treatment', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('result_relationship', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('result_stigma', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('result_total', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketa_app.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketa_app.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketa_app.hospital')),
            ],
        ),
    ]
